### ISSUE TITLE
ground with different ground types

### ISSUE THREAD

**Issue by totallyRonja** [axoila/NoTimeForApocalypse#8]
handle different ground types (max 3 per map)

**Comment by totallyRonja** [comment]
Shader implemented

**Comment by totallyRonja** [comment]
shader doesn't support alpha of src texture ronja fix pls

**Comment by totallyRonja** [comment]
shader with full alpha support done

**Comment by wockzn** [comment]
Grass and Dirt up

**Comment by totallyRonja** [comment]
basic ground is in, open new issue when new ground emerges
